USE [master]
GO
/****** Object:  Database [DataCopy]    Script Date: 2/19/2013 9:52:13 AM ******/
CREATE DATABASE [DataCopy]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DataCopy', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DataCopy.mdf' , SIZE = 4160KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DataCopy_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\DataCopy_log.ldf' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [DataCopy] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataCopy].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DataCopy] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DataCopy] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DataCopy] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DataCopy] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DataCopy] SET ARITHABORT OFF 
GO
ALTER DATABASE [DataCopy] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DataCopy] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [DataCopy] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DataCopy] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DataCopy] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DataCopy] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DataCopy] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DataCopy] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DataCopy] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DataCopy] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DataCopy] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DataCopy] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DataCopy] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DataCopy] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DataCopy] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DataCopy] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DataCopy] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DataCopy] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DataCopy] SET RECOVERY FULL 
GO
ALTER DATABASE [DataCopy] SET  MULTI_USER 
GO
ALTER DATABASE [DataCopy] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DataCopy] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DataCopy] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DataCopy] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'DataCopy', N'ON'
GO
USE [DataCopy]
GO
/****** Object:  Table [dbo].[KeywordCopyInfo]    Script Date: 2/19/2013 9:52:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[KeywordCopyInfo](
	[KeywordCopyInfoID] [int] IDENTITY(1,1) NOT NULL,
	[KeywordID] [int] NOT NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[LastestCopyRecordID] [int] NOT NULL,
	[LastestCopySubRecordID] [int] NOT NULL,
	[Status] [int] NOT NULL,
	[IsRunning] [bit] NOT NULL,
	[RunningDate] [datetime] NULL,
	[InsertedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_KeywordCopyInfoID] PRIMARY KEY CLUSTERED 
(
	[KeywordCopyInfoID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[RecordCopyLog]    Script Date: 2/19/2013 9:52:15 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecordCopyLog](
	[RecordCopyLogID] [int] IDENTITY(1,1) NOT NULL,
	[KeywordID] [int] NOT NULL,
	[RecordID] [int] NOT NULL,
	[DHRecordID] [int] NOT NULL,
	[InsertedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NOT NULL,
	[SubRecords] [int] NULL,
	[PublishedDate] [datetime] NULL,
 CONSTRAINT [PK_RecordCopyLogID] PRIMARY KEY CLUSTERED 
(
	[RecordCopyLogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
USE [master]
GO
ALTER DATABASE [DataCopy] SET  READ_WRITE 
GO
